name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Push to HF
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: AMIT-KARAR/QA_RAG_CHAIN_PDF_ASTRADB
          huggingface_repo_id: Amitkarar/RAG_QA_ASTRADB
          hf_token: ${{ secrets.HF_TOKEN }}
